import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import MainContainer from '../components/MainContainer'
import BgContainer from '../components/BgContainer'

export default function Home() {
  return (
    <div className={styles.containers}>
      <Head>
        <title>Eternal Return</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainContainer></MainContainer>
      <BgContainer></BgContainer>


    </div>
  )
}
