import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.containers}>
      <Head>
        <title>Eternal Return</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
      <div className={styles.header}>
        <div className={styles.header_logo}>
        <div className={styles.header_logo_logo}></div>
        </div>
        <div className={styles.header_menu}>
        <div className={styles.header_menu_text}>Heroes</div>
        <div className={styles.header_menu_text}>Help</div>
        <div className={styles.header_menu_text}>About</div>
        <div className={styles.header_menu_text_button}>
        <div className={styles.header_menu_text_button_play}>PLAY</div>
        </div>
        </div>
      </div>

      </div>
      <div className={styles.container}>
      <div className={styles.tringle}>
      <div className={styles.tringle_text}>
      </div>
      </div>
      <div className={styles.main}>
      <div className={styles.main_content}>
        <div className={styles.main_content_logo}></div>
        <div className={styles.main_content_platforms}>
                <div className={styles.main_content_platforms_steam}>
        
        </div>
        <div className={styles.main_content_platforms_steam}>
        
        </div>


        </div>
      </div>
      </div>
      </div>
      <div className={styles.container}>
        <div className={styles.news}>
          <div className={styles.news_title}>
          <div className={styles.news_title_text}>
          Heroes
          </div>
          </div>
          <div className={styles.news_heroes_container}>
          <div className={styles.news_heroes_block}>
          </div>
          <div className={styles.news_heroes_block_n}>
          </div>
          <div className={styles.news_heroes_block_r}>
          </div>
          <div className={styles.news_heroes_block_ch}>
          </div>
          <div className={styles.news_heroes_block}>
          </div>
          <div className={styles.news_heroes_block}>
          </div>
          <div className={styles.news_heroes_block}>
          </div>
          <div className={styles.news_heroes_block}>
          </div>
          <div className={styles.news_heroes_block}>
          </div>
          <div className={styles.news_heroes_block}>
          </div>
          <div className={styles.news_heroes_block}>
          </div>
          <div className={styles.news_heroes_block}>
          </div>
          <div className={styles.news_heroes_block}>
          </div>
          <div className={styles.news_heroes_block}>
          </div>
          <div className={styles.news_heroes_block}>
          </div>
          <div className={styles.news_heroes_block}>
          </div>
          <div className={styles.news_heroes_block}>
          </div>
          <div className={styles.news_heroes_block}>
          </div>
          <div className={styles.news_heroes_block}>
          </div>
          <div className={styles.news_heroes_block}>
          </div>
          <div className={styles.news_heroes_block}>
          </div>
          <div className={styles.news_heroes_block}>
          </div>
          <div className={styles.news_heroes_block}>
          </div>
          <div className={styles.news_heroes_block}>
          </div>
          <div className={styles.news_heroes_block}>
          </div>
          <div className={styles.news_heroes_block}>
          </div>
          <div className={styles.news_heroes_block}>
          </div>
          </div>
      </div>
      </div>

    </div>
  )
}
