import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import MainContainer from '../components/MainContainer'

export default function Home() {
  return (
    <div className={styles.containers}>
      <Head>
        <title>Eternal Return</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainContainer></MainContainer>
      <div className={styles.container}>
      <div className={styles.tringle}>
      <div className={styles.tringle_text}>
      </div>
      </div>
      <div className={styles.main}>
      <div className={styles.main_content}>
        <div className={styles.main_content_logo}></div>
        <div className={styles.main_content_platforms}>
                <div className={styles.main_content_platforms_steam}>
        
        </div>
        <div className={styles.main_content_platforms_steam}>
        
        </div>


        </div>
      </div>
      </div>
      </div>


    </div>
  )
}
